-- Monthly Market KPI View: year-over-year telecom market performance metrics by sub-system
-- Co-authored with CoCo

--------------------------------------------------------------------------------
-- PART 1: Year-over-Year Market KPI Table (2024 vs 2025)
--
-- Rebuilds a summary table comparing key performance indicators across markets.
-- Metrics include: footprint, revenue, growth, product mix, equipment, speed
-- tiers, and fiber adoption.
--
-- Replace placeholder database/schema references with your environment values:
--   <TARGET_DB>.<TARGET_SCHEMA>  — where the output table lives
--   <FOOTPRINT_DB>.<FOOTPRINT_SCHEMA> — footprint monthly fact view
--   <CAR_DB>.<CAR_SCHEMA>       — customer account record views
--------------------------------------------------------------------------------

DROP TABLE IF EXISTS <TARGET_DB>.<TARGET_SCHEMA>.AP_MARKET_KPI;

CREATE TABLE <TARGET_DB>.<TARGET_SCHEMA>.AP_MARKET_KPI AS
SELECT
    sys.SUB_SYSTEM_DESC,

    -- Homes Passed
    SUM(CASE WHEN foot.TIME_KEY = '2024-12-31' THEN foot.HOME_PASSED_CURR_CNT ELSE 0 END) AS homes_passed_2024,
    SUM(CASE WHEN foot.TIME_KEY = '2025-12-31' THEN foot.HOME_PASSED_CURR_CNT ELSE 0 END) AS homes_passed_2025,

    -- Subscribers
    SUM(CASE WHEN foot.TIME_KEY = '2024-12-31' THEN foot.SUBSCRIBER_CURR_CNT ELSE 0 END) AS subscribers_2024,
    SUM(CASE WHEN foot.TIME_KEY = '2025-12-31' THEN foot.SUBSCRIBER_CURR_CNT ELSE 0 END) AS subscribers_2025,

    -- Penetration %
    (SUM(CASE WHEN foot.TIME_KEY = '2024-12-31' THEN foot.SUBSCRIBER_CURR_CNT ELSE 0 END)
     / NULLIF(SUM(CASE WHEN foot.TIME_KEY = '2024-12-31' THEN foot.HOME_PASSED_CURR_CNT ELSE 0 END), 0)
    ) * 100 AS penetration_pct_2024,
    (SUM(CASE WHEN foot.TIME_KEY = '2025-12-31' THEN foot.SUBSCRIBER_CURR_CNT ELSE 0 END)
     / NULLIF(SUM(CASE WHEN foot.TIME_KEY = '2025-12-31' THEN foot.HOME_PASSED_CURR_CNT ELSE 0 END), 0)
    ) * 100 AS penetration_pct_2025,

    -- ARRPC (Average Revenue Per Customer)
    ROUND(
        SUM(CASE WHEN foot.TIME_KEY = '2024-12-31' THEN foot.TOTAL_NET_MRC_CURR_AMT ELSE 0 END)
        / NULLIF(SUM(CASE WHEN foot.TIME_KEY = '2024-12-31' THEN foot.SUBSCRIBER_CURR_CNT ELSE 0 END), 0),
    2) AS arrpc_2024,
    ROUND(
        SUM(CASE WHEN foot.TIME_KEY = '2025-12-31' THEN foot.TOTAL_NET_MRC_CURR_AMT ELSE 0 END)
        / NULLIF(SUM(CASE WHEN foot.TIME_KEY = '2025-12-31' THEN foot.SUBSCRIBER_CURR_CNT ELSE 0 END), 0),
    2) AS arrpc_2025,

    -- Connect Rate %
    (SUM(CASE WHEN foot.TIME_KEY = '2024-12-31' THEN foot.CONN_CNT ELSE 0 END)
     / NULLIF(SUM(CASE WHEN foot.TIME_KEY = '2024-12-31' THEN foot.NON_SUBSCRIBER_PREV_CNT ELSE 0 END), 0)
    ) * 100 AS connect_rate_pct_2024,
    (SUM(CASE WHEN foot.TIME_KEY = '2025-12-31' THEN foot.CONN_CNT ELSE 0 END)
     / NULLIF(SUM(CASE WHEN foot.TIME_KEY = '2025-12-31' THEN foot.NON_SUBSCRIBER_PREV_CNT ELSE 0 END), 0)
    ) * 100 AS connect_rate_pct_2025,

    -- Churn %
    (SUM(CASE WHEN foot.TIME_KEY = '2024-12-31' THEN foot.DISC_CNT ELSE 0 END)
     / NULLIF(SUM(CASE WHEN foot.TIME_KEY = '2024-12-31' THEN foot.SUBSCRIBER_PREV_CNT ELSE 0 END), 0)
    ) * 100 AS churn_pct_2024,
    (SUM(CASE WHEN foot.TIME_KEY = '2025-12-31' THEN foot.DISC_CNT ELSE 0 END)
     / NULLIF(SUM(CASE WHEN foot.TIME_KEY = '2025-12-31' THEN foot.SUBSCRIBER_PREV_CNT ELSE 0 END), 0)
    ) * 100 AS churn_pct_2025,

    -- Contract Renewal Eligible (based on TE code patterns)
    SUM(CASE WHEN foot.TIME_KEY = '2024-12-31' AND (
            car.CURR_TE_CODE_STRING LIKE '%RCR06RETCORE%'
         OR car.CURR_TE_CODE_STRING LIKE '%CR06ACQCORE%'
         OR car.CURR_TE_CODE_STRING LIKE '%CR01ACQCORE%'
         OR car.CURR_TE_CODE_STRING LIKE '%RCR01RETCORE%'
         OR car.CURR_TE_CODE_STRING LIKE '%CR02ACQCORE%'
         OR car.CURR_TE_CODE_STRING LIKE '%RCR02RETCORE%'
         OR car.CURR_TE_CODE_STRING LIKE '%RCR02RETNODUB%'
         OR car.CURR_TE_CODE_STRING LIKE '%CR03ACQCORE%'
         OR car.CURR_TE_CODE_STRING LIKE '%RCR03RETCORE%'
         OR car.CURR_TE_CODE_STRING LIKE '%CR04ACQCORE%'
         OR car.CURR_TE_CODE_STRING LIKE '%RCR04RETCORE%'
         OR car.CURR_TE_CODE_STRING LIKE '%RCR04RETNODUB%'
    ) THEN 1 ELSE 0 END) AS cr_eligible_2024,
    SUM(CASE WHEN foot.TIME_KEY = '2025-12-31' AND (
            car.CURR_TE_CODE_STRING LIKE '%RCR06RETCORE%'
         OR car.CURR_TE_CODE_STRING LIKE '%CR06ACQCORE%'
         OR car.CURR_TE_CODE_STRING LIKE '%CR01ACQCORE%'
         OR car.CURR_TE_CODE_STRING LIKE '%RCR01RETCORE%'
         OR car.CURR_TE_CODE_STRING LIKE '%CR02ACQCORE%'
         OR car.CURR_TE_CODE_STRING LIKE '%RCR02RETCORE%'
         OR car.CURR_TE_CODE_STRING LIKE '%RCR02RETNODUB%'
         OR car.CURR_TE_CODE_STRING LIKE '%CR03ACQCORE%'
         OR car.CURR_TE_CODE_STRING LIKE '%RCR03RETCORE%'
         OR car.CURR_TE_CODE_STRING LIKE '%CR04ACQCORE%'
         OR car.CURR_TE_CODE_STRING LIKE '%RCR04RETCORE%'
         OR car.CURR_TE_CODE_STRING LIKE '%RCR04RETNODUB%'
    ) THEN 1 ELSE 0 END) AS cr_eligible_2025,

    -- Product Subscribers (Internet, Voice, Video, Homelife, Mobile)
    SUM(CASE WHEN foot.TIME_KEY = '2024-12-31' AND foot.SUBSCRIBER_CURR_CNT = 1 AND psu.DATA_AFTER_FLG = 1 THEN 1 ELSE 0 END) AS internet_subscribers_2024,
    SUM(CASE WHEN foot.TIME_KEY = '2025-12-31' AND foot.SUBSCRIBER_CURR_CNT = 1 AND psu.DATA_AFTER_FLG = 1 THEN 1 ELSE 0 END) AS internet_subscribers_2025,
    SUM(CASE WHEN foot.TIME_KEY = '2024-12-31' AND foot.SUBSCRIBER_CURR_CNT = 1 AND psu.PHONE_AFTER_FLG = 1 THEN 1 ELSE 0 END) AS voice_subscribers_2024,
    SUM(CASE WHEN foot.TIME_KEY = '2025-12-31' AND foot.SUBSCRIBER_CURR_CNT = 1 AND psu.PHONE_AFTER_FLG = 1 THEN 1 ELSE 0 END) AS voice_subscribers_2025,
    SUM(CASE WHEN foot.TIME_KEY = '2024-12-31' AND foot.SUBSCRIBER_CURR_CNT = 1 AND psu.VIDEO_AFTER_FLG = 1 THEN 1 ELSE 0 END) AS video_subscribers_2024,
    SUM(CASE WHEN foot.TIME_KEY = '2025-12-31' AND foot.SUBSCRIBER_CURR_CNT = 1 AND psu.VIDEO_AFTER_FLG = 1 THEN 1 ELSE 0 END) AS video_subscribers_2025,
    SUM(CASE WHEN foot.TIME_KEY = '2024-12-31' AND foot.SUBSCRIBER_CURR_CNT = 1 AND psu.HOMELIFE_AFTER_FLG = 1 THEN 1 ELSE 0 END) AS homelife_subscribers_2024,
    SUM(CASE WHEN foot.TIME_KEY = '2025-12-31' AND foot.SUBSCRIBER_CURR_CNT = 1 AND psu.HOMELIFE_AFTER_FLG = 1 THEN 1 ELSE 0 END) AS homelife_subscribers_2025,
    SUM(CASE WHEN foot.TIME_KEY = '2024-12-31' AND foot.SUBSCRIBER_CURR_CNT = 1 AND wirls.CURR_MOBILE_FLAG = 1 THEN 1 ELSE 0 END) AS mobile_subscribers_2024,
    SUM(CASE WHEN foot.TIME_KEY = '2025-12-31' AND foot.SUBSCRIBER_CURR_CNT = 1 AND wirls.CURR_MOBILE_FLAG = 1 THEN 1 ELSE 0 END) AS mobile_subscribers_2025,

    -- Mobile Lines
    SUM(CASE WHEN foot.TIME_KEY = '2024-12-31' AND wirls.SUBSCR_EOP_CNT != 0 AND wirls.CURR_MOBILE_FLAG = 1 THEN wirls.SUBSCR_EOP_CNT ELSE 0 END) AS mobile_lines_2024,
    SUM(CASE WHEN foot.TIME_KEY = '2025-12-31' AND wirls.SUBSCR_EOP_CNT != 0 AND wirls.CURR_MOBILE_FLAG = 1 THEN wirls.SUBSCR_EOP_CNT ELSE 0 END) AS mobile_lines_2025,

    -- % Pano Wifi
    (SUM(CASE WHEN foot.TIME_KEY = '2024-12-31' AND foot.SUBSCRIBER_CURR_CNT = 1 AND car.PANO_FLAG = 1 AND psu.DATA_AFTER_FLG = 1 THEN 1 ELSE 0 END)
     / NULLIF(SUM(CASE WHEN foot.TIME_KEY = '2024-12-31' AND foot.SUBSCRIBER_CURR_CNT = 1 AND psu.DATA_AFTER_FLG = 1 THEN 1 ELSE 0 END), 0)
    ) * 100 AS pano_wifi_pct_2024,
    (SUM(CASE WHEN foot.TIME_KEY = '2025-12-31' AND foot.SUBSCRIBER_CURR_CNT = 1 AND car.PANO_FLAG = 1 AND psu.DATA_AFTER_FLG = 1 THEN 1 ELSE 0 END)
     / NULLIF(SUM(CASE WHEN foot.TIME_KEY = '2025-12-31' AND foot.SUBSCRIBER_CURR_CNT = 1 AND psu.DATA_AFTER_FLG = 1 THEN 1 ELSE 0 END), 0)
    ) * 100 AS pano_wifi_pct_2025,

    -- % BYOD
    (SUM(CASE WHEN foot.TIME_KEY = '2024-12-31' AND foot.SUBSCRIBER_CURR_CNT = 1 AND car.MODEM_BYOD_FLAG = 1 AND psu.DATA_AFTER_FLG = 1 THEN 1 ELSE 0 END)
     / NULLIF(SUM(CASE WHEN foot.TIME_KEY = '2024-12-31' AND foot.SUBSCRIBER_CURR_CNT = 1 AND psu.DATA_AFTER_FLG = 1 THEN 1 ELSE 0 END), 0)
    ) * 100 AS byod_pct_2024,
    (SUM(CASE WHEN foot.TIME_KEY = '2025-12-31' AND foot.SUBSCRIBER_CURR_CNT = 1 AND car.MODEM_BYOD_FLAG = 1 AND psu.DATA_AFTER_FLG = 1 THEN 1 ELSE 0 END)
     / NULLIF(SUM(CASE WHEN foot.TIME_KEY = '2025-12-31' AND foot.SUBSCRIBER_CURR_CNT = 1 AND psu.DATA_AFTER_FLG = 1 THEN 1 ELSE 0 END), 0)
    ) * 100 AS byod_pct_2025,

    -- Speed Tier Breakdown
    SUM(CASE WHEN foot.TIME_KEY = '2024-12-31' AND UPPER(tier.CHSI_SIMPLIFIED_TIER_AFTER_NM) IN (
        'ULTIMATE', 'GO EVEN FASTER INTERNET', 'STARTER', 'ULTIMATE CLASSIC',
        'GO FAST INTERNET', 'GO FASTER INTERNET', 'SEASONAL', 'CONNECT2COMPETE',
        'NO TIER', 'CONNECTASSIST', 'STRAIGHTUP', 'PREMIER', 'FAST INTERNET'
    ) THEN 1 ELSE 0 END) AS speed_500mbps_or_lower_2024,
    SUM(CASE WHEN foot.TIME_KEY = '2025-12-31' AND UPPER(tier.CHSI_SIMPLIFIED_TIER_AFTER_NM) IN (
        'ULTIMATE', 'GO EVEN FASTER INTERNET', 'STARTER', 'ULTIMATE CLASSIC',
        'GO FAST INTERNET', 'GO FASTER INTERNET', 'SEASONAL', 'CONNECT2COMPETE',
        'NO TIER', 'CONNECTASSIST', 'STRAIGHTUP', 'PREMIER', 'FAST INTERNET'
    ) THEN 1 ELSE 0 END) AS speed_500mbps_or_lower_2025,
    SUM(CASE WHEN foot.TIME_KEY = '2024-12-31' AND UPPER(tier.CHSI_SIMPLIFIED_TIER_AFTER_NM) = 'GO SUPER FAST INTERNET' THEN 1 ELSE 0 END) AS speed_1gig_2024,
    SUM(CASE WHEN foot.TIME_KEY = '2025-12-31' AND UPPER(tier.CHSI_SIMPLIFIED_TIER_AFTER_NM) = 'GO SUPER FAST INTERNET' THEN 1 ELSE 0 END) AS speed_1gig_2025,
    SUM(CASE WHEN foot.TIME_KEY = '2024-12-31' AND UPPER(tier.CHSI_SIMPLIFIED_TIER_AFTER_NM) = 'GO BEYOND FAST INTERNET' THEN 1 ELSE 0 END) AS speed_2gig_2024,
    SUM(CASE WHEN foot.TIME_KEY = '2025-12-31' AND UPPER(tier.CHSI_SIMPLIFIED_TIER_AFTER_NM) = 'GO BEYOND FAST INTERNET' THEN 1 ELSE 0 END) AS speed_2gig_2025,

    -- Fiber
    SUM(CASE WHEN foot.TIME_KEY = '2024-12-31' AND foot.HOME_PASSED_CURR_CNT = 1 AND LOWER(car.TRANSPORT_METHOD) = 'fiber' THEN 1 ELSE 0 END) AS fiber_enabled_homes_2024,
    SUM(CASE WHEN foot.TIME_KEY = '2025-12-31' AND foot.HOME_PASSED_CURR_CNT = 1 AND LOWER(car.TRANSPORT_METHOD) = 'fiber' THEN 1 ELSE 0 END) AS fiber_enabled_homes_2025,
    SUM(CASE WHEN foot.TIME_KEY = '2024-12-31' AND foot.HOME_PASSED_CURR_CNT = 1 AND LOWER(car.TRANSPORT_METHOD) = 'fiber' AND car.MODEM_FIBPONONT_FLAG = 1 THEN 1 ELSE 0 END) AS fiber_connected_subs_2024,
    SUM(CASE WHEN foot.TIME_KEY = '2025-12-31' AND foot.HOME_PASSED_CURR_CNT = 1 AND LOWER(car.TRANSPORT_METHOD) = 'fiber' AND car.MODEM_FIBPONONT_FLAG = 1 THEN 1 ELSE 0 END) AS fiber_connected_subs_2025

FROM <FOOTPRINT_DB>.<FOOTPRINT_SCHEMA>.CA_FOOTPRINT_MTHLY_FACT_V AS foot
INNER JOIN <CAR_DB>.<CAR_SCHEMA>.CA_CAR_MTHLY_FACT_V AS car
    ON  car.CUSTOMER_KEY = foot.CUSTOMER_KEY
    AND car.TIME_KEY     = foot.TIME_KEY
    AND car.HOUSE_KEY    = foot.HOUSE_KEY
INNER JOIN <CAR_DB>.<CAR_SCHEMA>.CA_PSU_MIGRATION_DIM_V AS psu
    ON foot.PSU_MIGRATION_KEY = psu.PSU_MIGRATION_KEY
INNER JOIN <CAR_DB>.<CAR_SCHEMA>.CA_WIRLS_CUSTOMER_MTHLY_FACT_V AS wirls
    ON  foot.CUSTOMER_KEY = wirls.CUSTOMER_KEY
    AND foot.TIME_KEY     = wirls.TIME_KEY
    AND foot.HOUSE_KEY    = wirls.HOUSE_KEY
INNER JOIN <CAR_DB>.<CAR_SCHEMA>.CA_CHSI_TIER_MIGRATION_DIM_V AS tier
    ON foot.CHSI_TIER_MIGRATION_KEY = tier.CHSI_TIER_MIGRATION_KEY
INNER JOIN <CAR_DB>.<CAR_SCHEMA>.CA_SUB_SYSTEM_DIM_V AS sys
    ON foot.SUB_SYSTEM_KEY = sys.SUB_SYSTEM_KEY
WHERE foot.TIME_KEY IN ('2024-12-31', '2025-12-31')
GROUP BY sys.SUB_SYSTEM_DESC
ORDER BY sys.SUB_SYSTEM_DESC ASC;


--------------------------------------------------------------------------------
-- PART 2: Current-Month Aggregate KPI Query (single-row total across all markets)
--
-- Same metrics as above but for the current month-end only.
-- Uncomment GROUP BY / ORDER BY to split by market.
--------------------------------------------------------------------------------

SELECT
    SUM(foot.HOME_PASSED_CURR_CNT) AS homes_passed,
    SUM(foot.SUBSCRIBER_CURR_CNT) AS subscribers,
    (SUM(foot.SUBSCRIBER_CURR_CNT) / NULLIF(SUM(foot.HOME_PASSED_CURR_CNT), 0)) * 100 AS penetration_pct,
    ROUND(SUM(foot.TOTAL_NET_MRC_CURR_AMT) / NULLIF(SUM(foot.SUBSCRIBER_CURR_CNT), 0), 2) AS arrpc,
    (SUM(foot.CONN_CNT) / NULLIF(SUM(foot.NON_SUBSCRIBER_PREV_CNT), 0)) * 100 AS connect_rate_pct,

    -- Contract Renewal Eligible
    SUM(CASE WHEN
            car.CURR_TE_CODE_STRING LIKE '%RCR06RETCORE%'
         OR car.CURR_TE_CODE_STRING LIKE '%CR06ACQCORE%'
         OR car.CURR_TE_CODE_STRING LIKE '%CR01ACQCORE%'
         OR car.CURR_TE_CODE_STRING LIKE '%RCR01RETCORE%'
         OR car.CURR_TE_CODE_STRING LIKE '%CR02ACQCORE%'
         OR car.CURR_TE_CODE_STRING LIKE '%RCR02RETCORE%'
         OR car.CURR_TE_CODE_STRING LIKE '%RCR02RETNODUB%'
         OR car.CURR_TE_CODE_STRING LIKE '%CR03ACQCORE%'
         OR car.CURR_TE_CODE_STRING LIKE '%RCR03RETCORE%'
         OR car.CURR_TE_CODE_STRING LIKE '%CR04ACQCORE%'
         OR car.CURR_TE_CODE_STRING LIKE '%RCR04RETCORE%'
         OR car.CURR_TE_CODE_STRING LIKE '%RCR04RETNODUB%'
    THEN 1 ELSE 0 END) AS cr_eligible,

    -- Product Subscribers
    SUM(CASE WHEN foot.SUBSCRIBER_CURR_CNT = 1 AND psu.DATA_AFTER_FLG = 1 THEN 1 ELSE 0 END) AS internet_subscribers,
    SUM(CASE WHEN foot.SUBSCRIBER_CURR_CNT = 1 AND psu.PHONE_AFTER_FLG = 1 THEN 1 ELSE 0 END) AS voice_subscribers,
    SUM(CASE WHEN foot.SUBSCRIBER_CURR_CNT = 1 AND psu.VIDEO_AFTER_FLG = 1 THEN 1 ELSE 0 END) AS video_subscribers,
    SUM(CASE WHEN foot.SUBSCRIBER_CURR_CNT = 1 AND psu.HOMELIFE_AFTER_FLG = 1 THEN 1 ELSE 0 END) AS homelife_subscribers,
    SUM(CASE WHEN foot.SUBSCRIBER_CURR_CNT = 1 AND wirls.CURR_MOBILE_FLAG = 1 THEN 1 ELSE 0 END) AS mobile_subscribers,
    SUM(CASE WHEN wirls.SUBSCR_EOP_CNT != 0 AND wirls.CURR_MOBILE_FLAG = 1 THEN wirls.SUBSCR_EOP_CNT ELSE 0 END) AS mobile_lines,

    -- Equipment Adoption
    (SUM(CASE WHEN foot.SUBSCRIBER_CURR_CNT = 1 AND car.PANO_FLAG = 1 AND psu.DATA_AFTER_FLG = 1 THEN 1 ELSE 0 END)
     / NULLIF(SUM(CASE WHEN foot.SUBSCRIBER_CURR_CNT = 1 AND psu.DATA_AFTER_FLG = 1 THEN 1 ELSE 0 END), 0)
    ) * 100 AS pano_wifi_pct,
    (SUM(CASE WHEN foot.SUBSCRIBER_CURR_CNT = 1 AND car.MODEM_BYOD_FLAG = 1 AND psu.DATA_AFTER_FLG = 1 THEN 1 ELSE 0 END)
     / NULLIF(SUM(CASE WHEN foot.SUBSCRIBER_CURR_CNT = 1 AND psu.DATA_AFTER_FLG = 1 THEN 1 ELSE 0 END), 0)
    ) * 100 AS byod_pct,

    -- Speed Tiers
    SUM(CASE WHEN UPPER(tier.CHSI_SIMPLIFIED_TIER_AFTER_NM) IN (
        'ULTIMATE', 'GO EVEN FASTER INTERNET', 'STARTER', 'ULTIMATE CLASSIC',
        'GO FAST INTERNET', 'GO FASTER INTERNET', 'SEASONAL', 'CONNECT2COMPETE',
        'NO TIER', 'CONNECTASSIST', 'STRAIGHTUP', 'PREMIER', 'FAST INTERNET'
    ) THEN 1 ELSE 0 END) AS speed_500mbps_or_lower,
    SUM(CASE WHEN UPPER(tier.CHSI_SIMPLIFIED_TIER_AFTER_NM) = 'GO SUPER FAST INTERNET' THEN 1 ELSE 0 END) AS speed_1gig,
    SUM(CASE WHEN UPPER(tier.CHSI_SIMPLIFIED_TIER_AFTER_NM) = 'GO BEYOND FAST INTERNET' THEN 1 ELSE 0 END) AS speed_2gig,

    -- Fiber
    SUM(CASE WHEN foot.HOME_PASSED_CURR_CNT = 1 AND LOWER(car.TRANSPORT_METHOD) = 'fiber' THEN 1 ELSE 0 END) AS fiber_enabled_homes,
    SUM(CASE WHEN foot.HOME_PASSED_CURR_CNT = 1 AND LOWER(car.TRANSPORT_METHOD) = 'fiber' AND car.MODEM_FIBPONONT_FLAG = 1 THEN 1 ELSE 0 END) AS fiber_connected_subs

FROM <FOOTPRINT_DB>.<FOOTPRINT_SCHEMA>.CA_FOOTPRINT_MTHLY_FACT_V AS foot
INNER JOIN <CAR_DB>.<CAR_SCHEMA>.CA_CAR_MTHLY_FACT_V AS car
    ON  car.CUSTOMER_KEY = foot.CUSTOMER_KEY
    AND car.TIME_KEY     = foot.TIME_KEY
    AND car.HOUSE_KEY    = foot.HOUSE_KEY
INNER JOIN <CAR_DB>.<CAR_SCHEMA>.CA_PSU_MIGRATION_DIM_V AS psu
    ON foot.PSU_MIGRATION_KEY = psu.PSU_MIGRATION_KEY
INNER JOIN <CAR_DB>.<CAR_SCHEMA>.CA_WIRLS_CUSTOMER_MTHLY_FACT_V AS wirls
    ON  foot.CUSTOMER_KEY = wirls.CUSTOMER_KEY
    AND foot.TIME_KEY     = wirls.TIME_KEY
    AND foot.HOUSE_KEY    = wirls.HOUSE_KEY
INNER JOIN <CAR_DB>.<CAR_SCHEMA>.CA_CHSI_TIER_MIGRATION_DIM_V AS tier
    ON foot.CHSI_TIER_MIGRATION_KEY = tier.CHSI_TIER_MIGRATION_KEY
INNER JOIN <CAR_DB>.<CAR_SCHEMA>.CA_SUB_SYSTEM_DIM_V AS sys
    ON foot.SUB_SYSTEM_KEY = sys.SUB_SYSTEM_KEY
WHERE foot.TIME_KEY = LAST_DAY(CURRENT_DATE);
-- GROUP BY sys.SUB_SYSTEM_DESC
-- ORDER BY sys.SUB_SYSTEM_DESC ASC;
